/* Catálogo Box & Co — Box Cajas Personalizadas (vitrina sin precios, solo imágenes).
   Imágenes en img/cajas/ — fotos provistas por Dani 11/08/2026. */
const CAJAS_PRODUCTS = [
  {"id":"caja-1","name":"Box Vino + Sal + Sacacorcho Automático","cat":"Box - Cajas Personalizadas","price":null,"img":"img/cajas/box-vino-sal-sacacorcho-auto.jpg","imgs":["img/cajas/box-vino-sal-sacacorcho-auto.jpg"],"desc":"Caja personalizada con vino Malbec, sal marina con especias y sacacorcho automático. Ideal como regalo corporativo premium.","tech":[],"tags":[]},
  {"id":"caja-2","name":"Box Vino + Sales + Sacacorcho","cat":"Box - Cajas Personalizadas","price":null,"img":"img/cajas/box-vino-sales-sacacorcho.jpg","imgs":["img/cajas/box-vino-sales-sacacorcho.jpg"],"desc":"Caja personalizada con vino Malbec, sales marinas finas y sacacorcho. Perfecta para clientes y colaboradores.","tech":[],"tags":[]},
  {"id":"caja-3","name":"Box Vino + Sales x4","cat":"Box - Cajas Personalizadas","price":null,"img":"img/cajas/box-vino-sales-x4.jpg","imgs":["img/cajas/box-vino-sales-x4.jpg"],"desc":"Caja personalizada con vino Malbec y cuatro sales marinas gourmet. Regalo empresarial elegante.","tech":[],"tags":[]},
  {"id":"caja-4","name":"Box Vino + Copa","cat":"Box - Cajas Personalizadas","price":null,"img":"img/cajas/box-vino-copa.jpg","imgs":["img/cajas/box-vino-copa.jpg"],"desc":"Caja personalizada con vino Malbec y copa de vino sin pie. Clásica y sofisticada.","tech":[],"tags":[]},
  {"id":"caja-5","name":"Box Vino + Sacacorcho","cat":"Box - Cajas Personalizadas","price":null,"img":"img/cajas/box-vino-sacacorcho.jpg","imgs":["img/cajas/box-vino-sacacorcho.jpg"],"desc":"Caja personalizada con vino Malbec y sacacorcho de colores. Un clásico que nunca falla.","tech":[],"tags":[]},
  {"id":"caja-6","name":"Box Vino + Copa + Sales x2","cat":"Box - Cajas Personalizadas","price":null,"img":"img/cajas/box-vino-copa-sales-x2.jpg","imgs":["img/cajas/box-vino-copa-sales-x2.jpg"],"desc":"Caja personalizada con vino Malbec, copa y dos sales gourmet. El combo completo.","tech":[],"tags":[]},
  {"id":"caja-7","name":"Box Vino + Sacacorcho Automático","cat":"Box - Cajas Personalizadas","price":null,"img":"img/cajas/box-vino-sacacorcho-auto.jpg","imgs":["img/cajas/box-vino-sacacorcho-auto.jpg"],"desc":"Caja personalizada con vino Malbec y sacacorcho automático. Práctica y moderna.","tech":[],"tags":[]},
  {"id":"caja-8","name":"Box Vino + Aireador","cat":"Box - Cajas Personalizadas","price":null,"img":"img/cajas/box-vino-aireador.jpg","imgs":["img/cajas/box-vino-aireador.jpg"],"desc":"Caja personalizada con vino Malbec y aireador de vino. Para los amantes del buen vino.","tech":[],"tags":[]}
];
